---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
   name: rabbitmq
   labels:
      app: rabbitmq
      project: roboshop
      service: rabbitmq
      env: dev
spec:
   ports:
      -  protocol: TCP
         port: 5672
         targetPort: 5672
   clusterIP: None
   selector:
      app: rabbitmq
      project: roboshop
      service: rabbitmq
      env: dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: rabbitmq
   labels:
      app: rabbitmq
      project: roboshop
      service: rabbitmq
      env: dev
spec:
   selector:
      matchLabels:
         app: rabbitmq
         project: roboshop
         service: rabbitmq
         env: dev
   serviceName: "rabbitmq"
   replicas: 1
   minReadySeconds: 10 # by default is 0
   template:
      metadata:
         labels:
            app: rabbitmq
            project: roboshop
            service: rabbitmq
            env: dev
      spec:
         serviceAccountName: rabbitmq
         terminationGracePeriodSeconds: 10
         containers:
            - name: rabbitmq
              image: rabbitmq
              ports:
                 - containerPort: 5672
              resources:
                 requests:
                    memory: "500Mi"
                    cpu: "250m"
                 limits:
                    memory: "500Mi"
                    cpu: "250m"
#              volumeMounts:
#                 - name: www
#                   mountPath: /usr/share/nginx/html
#   volumeClaimTemplates:
#      - metadata:
#           name: www
#        spec:
#           accessModes: [ "ReadWriteOnce" ]
#           storageClassName: "my-storage-class"
#           resources:
#              requests:
#                 storage: 1Gi