---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: mysql
---
apiVersion: v1
kind: Secret
metadata:
   name: mysql-cred
data:
   MYSQL_ROOT_PASSWORD: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: Service
metadata:
   name: mysqldb
   labels:
      app: mysql
      project: roboshop
      service: mysqldb
      env: dev
spec:
   ports:
      -  protocol: TCP
         port: 3306
         targetPort: 3306
   clusterIP: None
   selector:
      app: mysql
      project: roboshop
      service: mysqldb
      env: dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: mysql
   labels:
      app: mysql
      project: roboshop
      service: mysqldb
      env: dev
spec:
   selector:
      matchLabels:
         app: mysql
         project: roboshop
         service: mysqldb
         env: dev
   serviceName: "mysqldb"
   replicas: 1
   minReadySeconds: 10 # by default is 0
   template:
      metadata:
         labels:
            app: mysql
            project: roboshop
            service: mysqldb
            env: dev
      spec:
         serviceAccountName: mysql
         terminationGracePeriodSeconds: 10
         containers:
            - name: mysqldb
              image: hemanthtadikonda/mysql:1.0.0
              ports:
                 - containerPort: 3306
              env:
                 -  name: MYSQL_ROOT_PASSWORD
                    valueFrom:
                       secretKeyRef:
                          name: mysql-cred
                          key: MYSQL_ROOT_PASSWORD
              resources:
                 requests:
                    memory: "500Mi"
                    cpu: "250m"
                 limits:
                    memory: "500Mi"
                    cpu: "250m"
#              volumeMounts:
#                 - name: www
#                   mountPath: /usr/share/nginx/html
#   volumeClaimTemplates:
#      - metadata:
#           name: www
#        spec:
#           accessModes: [ "ReadWriteOnce" ]
#           storageClassName: "my-storage-class"
#           resources:
#              requests:
#                 storage: 1Gi