---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: mongodb
---
apiVersion: v1
kind: Service
metadata:
   name: mongodb
   labels:
      app: mongo
      project: roboshop
      service: mongo
      env: dev
spec:
   ports:
      -  protocol: TCP
         port: 27017
         targetPort: 27017
   clusterIP: None
   selector:
      app: mongo
      project: roboshop
      service: mongo
      env: dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: mongodb
   labels:
      app: mongo
      project: roboshop
      service: mongo
      env: dev
spec:
   selector:
      matchLabels:
         app: mongo
         project: roboshop
         service: mongo
         env: dev
   serviceName: "mongodb"
   replicas: 1
   minReadySeconds: 10 # by default is 0
   template:
      metadata:
         labels:
            app: mongo
            project: roboshop
            service: mongo
            env: dev
      spec:
         serviceAccountName: mongodb
         terminationGracePeriodSeconds: 10
         containers:
            - name: mongodb
              image: hemanthtadikonda/mongodb:1.0.0
              ports:
                 - containerPort: 27017
              resources:
                 requests:
                    memory: "500Mi"
                    cpu: "250m"
                 limits:
                    memory: "500Mi"
                    cpu: "250m"
#              volumeMounts:
#                 - name: www
#                   mountPath: /usr/share/nginx/html
#   volumeClaimTemplates:
#      - metadata:
#           name: www
#        spec:
#           accessModes: [ "ReadWriteOnce" ]
#           storageClassName: "my-storage-class"
#           resources:
#              requests:
#                 storage: 1Gi